name: Unittest

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # - name: Lint
      #   continue-on-error: true
      #   run: |
      #     pip install pip install flake8 flake8-csv \
      #     && flake8 --statistics --benchmark --doctests --format=csv_categories --tee --output-file artifacts/flake8.csv

      # - name: Static type check
      #   continue-on-error: true
      #   run: |
      #     pip install mypy lxml \
      #     && mypy --warn-unused-configs --python-version 3.8 --show-error-context --show-column-numbers --show-error-end --show-error-codes --pretty --html-report artifacts/statictypecheck --cobertura-xml-report statictypecheck competencias

      - name: Unit test
        continue-on-error: true
        run: |
          pip install -r requirements.txt -r requirements-dev.txt \
          && pytest --cov-report=xml --cov-report=html --cov-report=lcov --cov=competencias -s .

      - name: Archive QA artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            htmlcov/
            .coverage
            coverage.xml
            coverage.lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
